apiVersion: v1
data:
  config.json: "{\n    \"threeScaleMasterConfigUrl\": \"https://jqf8a3dt@test-master-3scale.192.168.99.123.nip.io\",
    \n    \"threeScaleAdminServiceUrl\": \"https://3scale-admin.3scale.192.168.99.123.nip.io\",
    \n    \"threeScaleServiceAuthToken\": \"4ead17e192709148fcb8b0e614b58ea00ac38c909d0c127ea15700f5919e73f7\",
    \n    \"serviceConfigs\": [\n        { \"name\":\"production\",\n            \"services\":
    [\n             {\n                \"id\":\"10001\",\n                \"type\":
    \"plain\",\n                \"token\": \"azp\"\n            },\n            {\n
    \               \"id\":\"10002\",\n                \"type\": \"plain\",\n                \"token\":
    \"client\"\n            },\n            {\n                \"id\":\"10002\",\n
    \               \"tenant_id\":\"10e001\",\n                \"type\": \"plain\",\n
    \               \"token\": \"aud\"\n            }\n        ]},\n        {\"name\":\"staging\",\n
    \           \"services\":[\n            {   \"id\" : \"1\",\n                \"type\":
    \"plain\",\n                \"token\": \"azp\"\n            },\n            {
    \"id\": \"3\",\n                \"type\": \"plain\",\n                \"token\":
    \"aud\"\n            }\n        ]}\n        ]\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: enricher-config
  selfLink: /api/v1/namespaces/3scale/configmaps/enricher-config
