apiVersion: v1
data:
  config.json: |-
    {
        "threeScaleAdminServiceUrl": "https://3scale-admin.3scale.192.168.99.123.nip.io",
        "threeScaleServiceAuthToken": "4ead17e192709148fcb8b0e614b58ea00ac38c909d0c127ea15700f5919e73f7",
    }
kind: ConfigMap
metadata:
  name: adminproxy-config
  labels:
    app: nodejs-adminproxy
