apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-adminproxy
  name: nodejs-adminproxy
  selfLink: /api/v1/namespaces/3scale/services/nodejs-adminproxy
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-adminproxy
  sessionAffinity: None
  type: ClusterIP

