apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: nodejs-adminproxy
  name: nodejs-adminproxy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: nodejs-adminproxy
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-adminproxy
        deploymentconfig: nodejs-adminproxy
    spec:
      containers:
      - env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: ENRICHER_CONFIG_FILE
          value: /enricher/config/config.json
        image: nodejs-adminproxy:latest
        imagePullPolicy: Always
        name: nodejs-enricher
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /enricher/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: adminproxy-config
        name: config-volume
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - nodejs-adminproxy
      from:
        kind: ImageStreamTag
        name: nodejs-adminproxy:latest
        namespace: 3scale
    type: ImageChange
  - type: ConfigChange
