apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-adminproxy
  name: nodejs-adminproxy

spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-adminproxy:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /nodejs
    git:
      ref: proxyOnly
      uri: https://github.com/fceresol/3ScaleConfigEnricher.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8/nodejs-16:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5


