kind: ImageStreamList
apiVersion: v1
metadata:
  annotations:
    description: NodeJS JSON 3Scale Admin Proxy image
  labels:
    app: nodejs-adminproxy
  name: nodejs-adminproxy
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nodejs-adminproxy
    annotations:
      openshift.io/display-name: nodejs-adminproxy
